- config/jest/svgrMock.js
Technically this may break some snapshot tests that have codifed the wrong value for src.  But it should also make a warning go away during the test run, so… that seems better.
> fix: make svgr mock produce better exports

- config/babel.config.js
Note that this will break translations for any repository using frontend-build and frontend-i18n.  Luckily, I don't think we have any of those.
> fix: update moduleSourceName to be @edx/frontend-platform/i18n

- config/webpack.prod.config.js
This allows projects that want to add optimizely to their headers to do so without overriding the HtmlWebpackPlugin configuration, which can be difficult and complicated (see frontend-app-payment’s webpack.prod.config.js for the difficulty in merging plugin configurations)
> feat: Allows adding an optimizely project ID into HtmlWebpackPlugin

- config/webpack.prod.config.js
This way it’s easier to search for / connect the dots.
Nothing's using this yet, so this is more of a fix than a change that might break things.
> fix: adjust optimizelyId to OPTIMIZELY_PROJECT_ID

- package-lock.json
- package.json
copy-webpack-plugin wasn’t being used and had a security vulnerability, so this removes it.  Also ran npm audit fix to fix around 2k+ vulnerabilities.
> fix: npm audit fix and removed copy-webpack-plugin

- README.rst
- config/webpack.dev.config.js
Allows frontend applications to define a module.config.js file with local overrides for modules loaded by their application.  See details in the README.
> feat: allow module.config.js for local module overrides

- config/webpack.dev.config.js
- config/webpack.prod.config.js
This PR adds the capability to configure the [publicPath](https://webpack.js.org/guides/public-path/) webpack configuration through environmental variables in order to allow the deployment of MFEs in custom paths.
> Add capability to configure publicPath of webpack through environmental variables.

- package-lock.json
- package.json
Upgrading `dotenv-webpack` to v3.0.0 introduced an issue where a `setImmediate` error is thrown in the console. This PR upgrades `dotenv-webpack` to v4.0.0 which was recently released with the fix for this issue.
See the following for more details:
* https://stackoverflow.com/questions/64232479/vue-js-webpack-i-get-setimmediate-js80-uncaught-syntaxerror-unexpected-token
* https://github.com/mrsteele/dotenv-webpack/issues/240
> fix(deps): upgrade dotenv-webpack to v4 to resolve errors with setImmediate

- config/webpack.dev.config.js
Using the new changes on the MFE caused me some troubles when I tried to use a custom path in the devstack due to historyApiFallback is not configured to use the publicPath, this PR aims to solve that problem.
I applied the solution suggested in https://github.com/webpack/webpack-dev-server/issues/1457#issuecomment-415527819, and it worked!
> fix: Configure historyApiFallback to use publicPath

- package-lock.json
- package.json
Why: need 2.22.1 minimum, to address issue with
import/no-cycles rule in eslint. Was encountered
while working on
https://github.com/edx/frontend-enterprise/pull/21
Ref: https://github.com/airbnb/javascript/issues/2331#issuecomment-724114465
How did I test this?
```
Error: .eslintrc » eslint-config-airbnb » /node_modules/eslint-config-airbnb-base/index.js » /node_modules/eslint-config-airbnb-base/rules/imports.js:
Configuration for rule "import/no-cycle" is invalid:
Value "∞" should be integer.
```
> ENT-3691: update eslint-plugin-import

- config/webpack.dev.config.js
This commit adds the css auto-prefixer into the dev postcss webpack routine, in order to assure that code loads the same style values in production and development.
> autoprefix css in dev builds

- package-lock.json
- package.json
There’s a documented issue in “imagemin-gifsicle” where a recent update (5.0.0) removed the binaries for linux distributions:
https://github.com/imagemin/gifsicle-bin/issues/113
https://github.com/tcoopman/image-webpack-loader/issues/233
This causes it to explode in CI via our direct dependency on image-webpack-loader.  The 7.0.0 version of image-webpack-loader relies on version 5 of gifsicle.  If we downgrade back to 6.0.0, we get gifsicle 4.0.1 instead, which still has the binaries.
I'm also noticing that the source for gifsicle is a bit confusing.  There's two projects here:
https://github.com/imagemin/imagemin-gifsicle
https://github.com/imagemin/gifsicle-bin
gifsicle-bin is the one that needs to be downgraded to 4.0.1 from 5.0.0.  imagemin-gifsicle also gets downgraded from 7.0.0 to …
> fix: Downgrading image-webpack-loader to fix linux arch bug in gifsicle

- README.rst
- config/webpack.dev-stage.config.js
- config/webpack.dev.config.js
- lib/resolvePrivateEnvConfig.js
This PR adds support for the proposed feature as outlined in: https://github.com/edx/frontend-build/issues/140
You may now create a `.gitignored`'ed .env.private file in any repo that uses edx/frontend-build's Webpack configs to override environment variables defined in .env.development and .env.development-stage.
> feat: allow private overrides of dev env vars

- package-lock.json
- package.json
Related ticket: https://openedx.atlassian.net/browse/FEDX-562
This PR bumps react-dev-utils to latest to bring in `immer` v8.0.1, resolving a vulnerability which was causing frontend-app-payment's pre-commit hook to fail.
https://npmjs.com/advisories/1603
Releasing this upgrade as a patch since it shouldn't affect how we develop locally with React.
> fix: upgrade react-dev-utils to resolve vulnerability in immer

- config/webpack.dev-stage.config.js
- config/webpack.dev.config.js
We’ve been seeing errors in MFEs using frontend-build 5.6.10 where they were unable to connect to webpack-dev-server for hot reloading, and it was making the server shut down.
The server would error out with:
```
events.js:292
throw er; // Unhandled 'error' event
^
Error: read ECONNRESET
at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on Socket instance at:
at emitErrorNT (internal/streams/destroy.js:92:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
at processTicksAndRejections (internal/process/task_queues.js:84:21) {
errno: 'ECONNRESET',
code: 'ECONNRESET',
syscall: 'read'
}
```
And the client would error out with a message like:
```
WebSocket connection to 'ws://localhost:8735/sockjs-node' failed:
```
The fix was to set `transportMode` …
> fix: configure webpackHotDevClient properly

- config/webpack.prod.config.js
- package-lock.json
Utilizes the already installed `NewRelicSourceMapPlugin` NPM package in webpack.prod.config.js to upload source maps to New Relic for production builds.
With source maps uploaded to New Relic, viewing the unminified stack trace for JS errors occurs automatically as opposed to needing to manually upload a source map file.
> feat: use NewRelicSourceMapPlugin to upload source maps to New Relic

- .eslintignore
- config/babel.config.js
- example/package.json
- example/src/App.jsx
- example/src/App.test.jsx
- example/src/index.jsx
- package-lock.json
- package.json
This updates the @babel/preset-react configuration to use the new JSX transform, which no longer requires `React` to be imported into source files.
It also updates our eslint-config to no longer require that `React` be imported into source files as well.
This works because our babel (7.9.0+) and react (16.14.0+) versions are high enough that they can take advantage of the new JSX transform.
Note that this means this version of frontend-build has a new peer dependency on react > 16.14.0, to ensure that it has the new JSX transform available.
> feat: use new jsx transform

- README.rst
Recent changes to devstack allow installation of local
NPM packages for MFEs running in devstack. However,
it requires shared NPM packages to be placed at a specific
location: ../src. Update this repo's docs to reflect that.
https://openedx.atlassian.net/browse/TNL-8407
Related to https://github.com/edx/devstack/pull/783
> docs: update docs on local module configuration

- package-lock.json
- package.json
This updates:
- webpack from 5.44.0 -> 5.50.0
- webpack-cli from 4.7.2 -> 4.8.0
- webpack-dev-server from 4.0.0-beta.3 -> 4.0.0-rc.1
It's the last one that's most interesting.  A bug has emerged in beta.3 which is preventing some of our projects from building correctly.  See comments here: https://github.com/webpack/webpack-cli/issues/2894#issuecomment-899432497
Hoping this fixes our issues.
> fix: updating webpack dependencies to latest

- config/webpack.dev-stage.config.js
- config/webpack.dev.config.js
v4 of webpack-dev-server has a breaking change where the 'transportMode' configuration for the dev server was changed to 'webSocketServer', effectively.
See migration guide here: https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md
> fix: update devServer config to use webSocketServer

- config/webpack.prod.config.js
By defining the `ENABLE_NEW_RELIC='false'` environment variable, the new relic
logging integration will be disabled, which is a must-have for most non-edX
platforms.
Close https://github.com/openedx/frontend-wg/issues/14
cc @davidjoy.
> feat: make it possible to disable NewRelic globally

- package-lock.json
- package.json
[This upstream PR](https://github.com/tcoopman/image-webpack-loader/pull/413) was merged and released for `image-webpack-loader` to upgrade `imagemin-webp` from v6 to v7 to remove its dependency on `trim-newlines` which has a "High" security vulnerability at its current version.
As a result, we can upgrade to this new version of `image-webpack-loader` to resolve our security dependency.
> fix: upgrade image-webpack-loader to 8.1.0

- config/webpack.dev-stage.config.js
- config/webpack.dev.config.js
- config/webpack.prod.config.js
By default, `PostCssAutoprefixerPlugin` will not autoprefix `grid`-based properties, unless it is explicitly enabled, which we are doing in frontend-build's Webpack configs. As we no longer officially support older browsers like IE 11, we no longer have a need to autoprefix `grid` properties. More details about `grid` and autoprefixer may be found [here](https://github.com/postcss/autoprefixer#does-autoprefixer-polyfill-grid-layout-for-ie).
A new Paragon component (`SelectableBox`) utilizes the CSS `grid` properties, but when upgrading an MFE to the Paragon version with this new component, there are Webpack build warnings related to autoprefixer not supporting the `grid-auto-rows` property:
In order for the MFE to build properly on this Paragon version is to have `grid` autoprefix …
> fix: remove grid option from PostCssAutoprefixerPlugin

- package-lock.json
- package.json
This PR updates frontend-build's version of webpack-dev-server to 4.7.3, to incorporate fix to vulnerability in dependent package node-forge. 
Issue is logged here:  https://github.com/openedx/frontend-wg/issues/82
> chore: update webpack-dev-server

- package-lock.json
Ran `npm audit fix` (_not_ forced) to get fixes for some high-severity security issues, notably:
> minimist  <=1.2.5
> Severity: high
> Prototype Pollution in minimist - https://github.com/advisories/GHSA-xvch-5gv4-984h
> fix available via `npm audit fix`
> node_modules/minimist
> 
> node-forge  <1.3.0
> Severity: high
> Improper Verification of Cryptographic Signature in node-forge - https://github.com/advisories/GHSA-cfm4-qjh2-4765
> fix available via `npm audit fix`
> node_modules/node-forge
Also hoping this will change the circumstances of the [heisenbug #85](https://github.com/openedx/frontend-wg/issues/85) which is blocking frontend-app-payment
> fix: ran npm audit fix for some high-severity security updates

- config/webpack.dev.config.js
This will allow dev environments to include the Optimizely script snippet via index.html,
which we know we need in at least two consuming MFEs.
This should be fine for any downstream consumers that don't use Optimizely, because
we tend to conditionally include an Optimizely script in index.html based on the existence of
an OPTIMIZELY_PROJECT_ID variable in the environment (i.e. in `.env.development`). So if
that variable is not present by default (which it shouldn't be), no Optimizely script is included.
Example downstream consumers that want this:
* enterprise admin-portal
* enterprise learner-portal
* relevant ticket: https://openedx.atlassian.net/browse/ENT-5726
> feat: Include OPTIMIZELY_PROJECT_ID in the HtmlWebpackPlugic dev config.

- package-lock.json
- package.json
`@edx/frontend-platform` currently denotes a `react` as a peer dependency at version 16.9.0, which other libraries in our frontend infrastructure specifies `react` as a peer dependency at version 16.12.0+:
https://github.com/openedx/frontend-platform/blob/master/package.json#L76
To avoid peer dependency conflicts when installing packages on Node 16 / NPM 8+, we should expand the `react` peer dependency range here to match what's currently expected by `@edx/frontend-platform`.
> fix: expand react peer dependency range to be compatible with `@edx/frontend-platform`

- package-lock.json
- package.json
BREAKING CHANGE: By upgrading to `@edx/eslint-config` v3, we will start extending `airbnb/hooks` and consumers of this library will now get ESLint errors about React Hooks:
1. Rules of Hooks.
2. Exhaustive dependencies.
See https://github.com/airbnb/javascript/blob/fdc812a0a5773449274f7c4d473e0841eca89614/packages/eslint-config-airbnb/rules/react-hooks.js for more details.
> feat: upgrade @edx/eslint-config to lint React Hooks

- config/.eslintrc.js
**Ticket:** 
[@edx/frontend-build v12+ is not properly linting with eslint](https://github.com/openedx/frontend-wg/issues/114)
**What has changed:**
- Without configFile, linting was not working properly. Updated configFile in eslintrc to fix linting issue.
> Added configFile to fix linting issue

- bin/fedx-scripts.js
**Ticket:** 
[@edx/frontend-build v12+ is not properly linting with eslint](https://github.com/openedx/frontend-wg/issues/114)
**What has changed:**
- Updated `fedx-scripts`, to require `eslint` in order to resolve `linting` issues on consumer side. [Previously we were using `'eslint/bin/eslint'` to load eslint in `fedx-scripts `but with v8 upgrade that failed. Beginning with v8.0.0, ESLint is strictly defining its public API. Previously, we could reach into individual files such as require("eslint/bin/eslint") but this is no longer allowed]
> fix: added updated fedx-scripts eslint path

- config/.eslintrc.js
**Ticket:**
[115: ignore ESLint for `module.config.js` file](https://github.com/openedx/frontend-wg/issues/115)
**What changed?**
- Ignored ESLint for `module.config.js` file.
> Ignored eslint for module.config.js

- .eslintrc.js
When we updated eslint to v8, more rules were added by default. This turns off rules that we don't want. It also forces arrow function syntax for functional react components.
> chore: update linting rules to prevent warnings

- .eslintrc.js
We've added rules to force repo consistency for functional components, and have turned off rules around module import warnings.
If you decide arrow functions aren't right for your particular project, feel free to override them, and keep your repo consistent with named functions. Override guidance is in the README of this repo, and I will be creating a comment about this decision for the cookie cutter template.
> feat: add new accepted linting rules for functional components and module imports

- config/babel-typescript.config.js
- config/webpack.dev.config.js
- lib/presets.js
- package-lock.json
- package.json
This PR adds TypeScript support to `dev` config to be able to build project with TypeScript files. Otherwise the build fails as was found during working with Paragon.
> [BD-46] Add typescript support for dev config

- package-lock.json
- package.json
There is a breaking change that affect us. https://github.com/formatjs/formatjs/commit/47ca556c1405eec7b7b2660275ae84a019112b2b
`messageDir` is being remove. There is also a desire to remove replace `babel-plugin-react-intl` with `babel-plugin-formatjs`.  https://github.com/openedx/frontend-wg/issues/120
Reverts openedx/frontend-build#116
> Revert "fix(deps): update dependency babel-plugin-react-intl to v8"

- README.rst
- config/jest.config.js
- config/webpack.prod.config.js
- example/src/App.jsx
- example/src/Image.tsx
- example/src/__snapshots__/App.test.jsx.snap
- package-lock.json
- package.json
- tsconfig.json
Client MFE's are beginning to move towards using typescript (see https://github.com/openedx/frontend-app-admin-portal/pull/957), and so we want to enable it for production.
> feat: Enable typescript for production builds

- README.rst
- tsconfig.json
- Remove stray apostrophe from tsconfig path
- Add instructions around the tsconfig 'outDir' variable when configuring in a new repo
> fix: Fix and additional documentation for tsconfig

- config/webpack.dev-stage.config.js
- config/webpack.dev.config.js
- config/webpack.prod.config.js
- package-lock.json
- package.json
-  Ensure we can generate `@custom-media` from design tokens with style-dictionary.
-  Ensure we add support for `postcss-custom-media` to @edx/frontend-build's default Webpack configs for all MFEs.
Issue: https://github.com/openedx/paragon/issues/2015
> [BD-46] feat: added CSS custom media query support

- README.rst
- config/webpack.prod.config.js
- package-lock.json
- package.json
This is ready again for review, see below for testing detials and result
~~[Update] 18.01.22 As of testing with olive MFE learning, the CSS output was missing a lot of stuff. Converted to draft again, need to double check the correct settings~~
The added plugin, reduce the CSS file by removing unused CSS
The plugin is kinda recommended by bootstrap[^1], reducing
unused CSS is generally recommended as well enchance web
perforamce[^2]
[^1]: https://getbootstrap.com/docs/5.2/customize/optimize/#unused-css
[^2]: https://web.dev/css-web-vitals/#critical-css
Related issue: openedx/frontend-wg/issues/138
This is still work on progress, I need to do further testing, to ensure this change doesn't break styling or any other thing
> feat: reduce size CSS output file

- .github/workflows/sync-master-alpha.yml
As we are introducing an `alpha` distribution of `@edx/frontend-build`, it will be helpful to have automation in place to sync changes to `master` with the `alpha` branch so the `alpha` branch doesn't get quickly outdated.
The intent is to have the generated PR  auto-merged to bring changes from `master` to `alpha` automatically.
I changed the Settings for this repo to enable auto-merge and added a branch protection rule to `alpha` branch.
> build: add github action workflow to auto-sync master to alpha

- config/webpack.dev-stage.config.js
- config/webpack.dev.config.js
Ran into this issue trying to use an MFE route that contains a course key with a period (e.g., `MITx+CTL.SC2x`) in two different MFEs relying on standard development webpack configs from `@edx/frontend-build`:
This PR sets `disableDotRule: true` for the `historyApiFallback` configuration to make it possible to load MFE routes with a period (`.`) in them without issue.
Docs: https://github.com/bripkens/connect-history-api-fallback#disabledotrule
> fix: disable dot rule in historyApiFallback in webpack.dev.config.js files.

- lib/scripts/serve.js
When upgrading to the latest version of frontend-build in an Enterprise MFE, the server port was not detecting the port in the .env.development file as expected... this PR ensures it should run on the expected `PORT`.
> fix: ensure .env.development PORT works

- config/webpack.dev-stage.config.js
- config/webpack.dev.config.js
- config/webpack.prod.config.js
https://sass-lang.com/documentation/js-api/interfaces/options/#quietDeps
> If this option is set to true, Sass won’t print warnings that are caused by dependencies. A “dependency” is defined as any file that’s loaded through [loadPaths](https://sass-lang.com/documentation/js-api/interfaces/Options#loadPaths) or [importers](https://sass-lang.com/documentation/js-api/interfaces/Options#importers). Stylesheets that are imported relative to the entrypoint are not considered dependencies.
https://github.com/twbs/bootstrap/issues/34051
Example deprecation warnings seen throughout MFEs (common issue):
```
WARNING in ./src/index.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].use[2]!./node_modules/resolve-url-lo …
```
> fix: silence sass compiler warnings about Dart Sass deprecations

- config/webpack.common.config.js
This PR fixes errors generated by source-maps-loader for some packages.
Careful consideration is taken to only ignore issues generated by node modules as some third party packages may ship miss-configured sourcemaps, that interrupts the build.
See: https://github.com/facebook/create-react-app/discussions/11278#discussioncomment-1780169 and https://github.com/facebook/create-react-app/pull/11752
This PR fixes https://github.com/openedx/paragon/issues/1674
On running `npm run build` on any of the MFE's you would have an error similar to the below 
The error to look out for here is `Failed to parse source map`
After this fix the error should be gone and not show up on running `npm run build`.
Some MFE's have multiple of these errors and should be gone also.
Fixes: …
> fix: errors generated by source maps loader

- package-lock.json
- package.json
Move ts-jest to devDependencies.  This seems to allow the install step to put it in node_modules/.bin even when installed as a dependency, which is necessary to allow the jest config to work.
> fix: install ts-jest as dev dependency to ensure winds up in consuming bin files

- config/.eslintrc.next.js
- lib/presets.js
- package-lock.json
- package.json
This adds support for formatjs eslint rules, and adds an `eslint-next`config which includes a rule that ensures all translation source strings have descriptions.
Verified working via https://github.com/openedx/frontend-app-learning/pull/1319
> feat: support formatjs eslint rules

- package-lock.json
- package.json
The shared `@edx/eslint-config` was recently updated to support the `es2020` environment such that syntax like `globalThis` won't cause linting errors.
This PR bumps the version of `@edx/eslint-config` to pull in this change for consuming MFEs and shared JS libraries (e.g., frontend-platform).
> fix: bump shared eslint config version

- catalog-info.yml
This PR adds the `catalog-info.yaml` file for backstage.
> build: Add structured Maintainers information

- config/jest.config.js
Currently, `ts` and `tsx` files are not included in the coverage report. This PR updates the `collectCoverageFrom` param from `jest.config` to fix the issue.
[Here](https://github.com/openedx/frontend-app-course-authoring/pull/1155) is a `course-autoring` PR using a version with this change and the coverage report [including ts files](https://app.codecov.io/gh/openedx/frontend-app-course-authoring/commit/e99a176adf50d15662a3c711ed836ad79af35ccc/indirect-changes?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr%20comments&utm_term=openedx).
> fix: add typescript files to coverage report

- package-lock.json
- package.json
Upgrades `@edx/typescript-config` to latest version (1.1.0) to pull in recent updates introduced by https://github.com/openedx/typescript-config/pull/12.
Issues and resolutions:
* `.tsx` files need to import `React` global; migrates to new JSX transform for parity with `.jsx` files, where `React` import is no longer needed.
* Later/modern JS syntax like `.replaceAll()` not supported; updates lib to include "ESNext" (matches create-react-app's TS config and @davidjoy frontend-base).
* Dynamic imports not supported; migrates to module: "ESNext"
> fix: upgrade @edx/typescript-config to 1.1.0

- package-lock.json
- package.json
Pulls in https://github.com/openedx/eslint-config/pull/156 : "feat: Don't require defaultProps for function components"
> chore(deps): update @edx/eslint-config to 4.2.0

- config/jest.config.js
When attempting to run a Jest test with the `watch` flag, (Ex. `npm run test:watch`) within the `frontend-app-admin-portal` repository, I ran into an issue where the Jest watch would not initiate and would trigger the following error:
Adding the configuration field `watchPathIgnorePatterns` to the jest config file to ignore the node modules directory when running a Jest watch. The inclusion of this field resolved the error locally as an override field in `jest.config.js`, but I am proposing to add it within `frontend-build`'s `jest.config.js` configuration directly.
> fix: ignore node_modules path for jest watchman

- package-lock.json
- package.json
Bump eslint so that we get the new rules that were merged in https://github.com/openedx/eslint-config/pull/164.
> chore: bump eslint

- config/webpack.dev-stage.config.js
- config/webpack.dev.config.js
- config/webpack.prod.config.js
Enable config-based setting of `<meta name="robots" content="{value}">` tag to allow MFEs to instruct search crawlers / indexers how to handle their content.
Related PRs:
- https://github.com/openedx/frontend-app-learning/pull/1520
See also:
- [Robots meta tag reference](https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag)
- [AU-2285](https://2u-internal.atlassian.net/browse/AU-2285)
> feat: allow setting robots content attribute through config

- config/webpack.dev-stage.config.js
- config/webpack.dev.config.js
- config/webpack.prod.config.js
- package-lock.json
- package.json
This upgrades `sass` and silences the many deprecation warnings that result.
Without this, MFEs may bump the sass version anyways, and then they'll see this ugliness when starting the dev server:
> Upgrade 'sass' to 1.85.1, silence new deprecation warnings

- config/webpack.common.config.js
- example/src/index.tsx
- example/tsconfig.json
The release of 14.4.0 to make Webpack and ESlint aware of `paths` defined in `tsconfig.json` breaks MFEs that have not yet adopted TypeScript, as described [here](https://github.com/openedx/frontend-build/pull/636#issuecomment-2760211733). If a project does't define `tsconfig.json`, `tsconfig-paths-webpack-plugin` will unexpectedly throw an error due to the missing file.
```shell
> @edx/frontend-app-learner-dashboard@0.0.1 build
> fedx-scripts webpack
Running with resolved config:
/home/runner/work/frontend-app-learner-dashboard/frontend-app-learner-dashboard/webpack.prod.config.js
[webpack-cli] Failed to load '/home/runner/work/frontend-app-learner-dashboard/frontend-app-learner-dashboard/webpack.prod.config.js' config
[webpack-cli] Error: ENOENT: no such file or directory, stat …
```
> fix: ensure TsconfigPathsPlugin is only added if tsconfig.json exists

- config/webpack.dev-stage.config.js
- config/webpack.dev.config.js
- config/webpack.prod.config.js
Resolves https://github.com/openedx/paragon/issues/3514
> fix: configure `PostCssAutoprefixerPlugin` to not remove vendor prefixes

- bin/fedx-scripts.js
Enhance the `fedx-scripts.js` script on `formatjs` with an option to extract translations on additional source folders.
Example:
`--include=plugins --include=plugins2`
This PR is required to fix the extraction process on the https://github.com/openedx/frontend-app-authoring/ because there are an additional [`plugins` source folder](https://github.com/openedx/frontend-app-authoring/tree/master/plugins/course-apps).
Then the next step is to change the `i18n_extract` on package.json to include the additional folder on https://github.com/openedx/frontend-app-authoring/blob/04faf54ad8ca74a288c872f1140eafc0aa4f9763/package.json#L14
From:
```json
"i18n_extract": "fedx-scripts formatjs extract",
```
To:
```json
"i18n_extract": "fedx-scripts formatjs extract --include=plugins",
```
Additionally it …
> feat(formatjs): support additional src folders

- config/babel.config.js
Incorrect lodash imports are causing MFEs to import the entire lodash library. This change shaves off a few kB of every MFE compressed build.
> feat: lighter build by rewriting lodash imports
